var user = {
  "login": "DustinGuthrie",
  "id": 14365991,
  "avatar_url": "https://avatars.githubusercontent.com/u/14365991?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/DustinGuthrie",
  "html_url": "https://github.com/DustinGuthrie",
  "followers_url": "https://api.github.com/users/DustinGuthrie/followers",
  "following_url": "https://api.github.com/users/DustinGuthrie/following{/other_user}",
  "gists_url": "https://api.github.com/users/DustinGuthrie/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/DustinGuthrie/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/DustinGuthrie/subscriptions",
  "organizations_url": "https://api.github.com/users/DustinGuthrie/orgs",
  "repos_url": "https://api.github.com/users/DustinGuthrie/repos",
  "events_url": "https://api.github.com/users/DustinGuthrie/events{/privacy}",
  "received_events_url": "https://api.github.com/users/DustinGuthrie/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dustin Guthrie",
  "company": null,
  "blog": null,
  "location": "Charleston SC",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2015-09-20T00:55:15Z",
  "updated_at": "2015-10-07T18:01:20Z"
}
